teto:
  # Enable or disable the plugin.
  enabled: true

random-spawns:
  # Spawn locations are in random_spawn_locations.yml.
  # RANDOM SPAWNS ARE A WIP, DO NOT ENABLE UNLESS TESTING
  enabled: false
  # Blocks/tags players can spawn on. Uses Spigot material and tag names.
  allowed-spawn-blocks:
    - MOSS_BLOCK
    - STONE
    - GRAVEL
  allowed-spawn-tags:
    - DIRT
    - SAND
    - LOGS
    - LEAVES
  # Used to determine if a spawn is inside the world border. Since TEAW
  # doesn't use the vanilla world border, we have to do this.
  world-border:
    sw-corner:  # Southwest corner
      x: -18430
      z: -275
    ne-corner:  # Northeast corner
      x: 7070
      z: -9201
